language: php

sudo: false

php:
- 5.3
- 5.4
- 5.5
- 5.6
- hhvm
- 7.0

env:
- WP_VERSION=latest WP_MULTISITE=0
- WP_VERSION=4.2 WP_MULTISITE=0

matrix:
  allow_failures:
  - php: hhvm
  - php: 7.0

before_script:
- echo -e "Host bitbucket.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- bash tests/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
- composer self-update
- composer install --no-interaction

script:
- if [[ $TRAVIS_PHP_VERSION = '5.5' && $WP_VERSION = 'latest'
  ]]; then phpunit --coverage-clover=coverage.clover; else phpunit; fi

after_script:
- if [[ $TRAVIS_PHP_VERSION = '5.5' && $WP_VERSION = 'latest' ]] ; then
    bash <(curl -s https://codecov.io/bash)
  fi

git:
  depth: 1